apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-trigger-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-trigger-role
rules:
  - apiGroups: [batch]
    verbs: [get]
    resources: [cronjobs]
  - apiGroups: [batch]
    verbs: [create]
    resources: [jobs]
