resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: cronjob-trigger
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
