apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-trigger
  labels:
    app: cronjob-trigger
spec:
  replicas: 1
  template:
    metadata:
      name: cronjob-trigger
      labels:
        app: cronjob-trigger
    spec:
      serviceAccountName: cronjob-trigger-sa
      containers:
        - name: cronjob-trigger
          image: cronjob-trigger
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
  selector:
    matchLabels:
      app: cronjob-trigger
